---
# https://taskfile.dev
version: '3'

env:
  ENV: testing
dotenv: ['.env', '.env.{{.ENV}}']

includes:
  dr_mcp:
    taskfile: ./dr_mcp/Taskfile.yaml
    dir: ./dr_mcp
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra

tasks:
  default:
    desc: "ℹ️ Show all available tasks (run `task --list-all` to see hidden tasks)"
    cmds:
      - task --list --sort none
    silent: true

  lint:
    desc: "🧹 Run linters"
    cmds:
      - task: dr_mcp:lint
      - task: infra:lint

  install:
    desc: "🛠️ Install dependencies"
    cmds:
      - task: dr_mcp:install
      - task: infra:install

  test:
    desc: "🧪 Run tests"
    cmds:
      - task: dr_mcp:test

  dev:
    desc: "🚀 Run all services together"
    cmds:
      - task dr_mcp:dev

  deploy:
    desc: "🚀 Deploy all services"
    cmds:
      - task: install
      - task: infra:deploy

  refresh:
    desc: "⚪️ Run Pulumi refresh"
    cmds:
      - echo "Running pulumi refresh"
      - cd ./infra && uv run pulumi refresh
    silent: true

  destroy:
    desc: "🔴 Run Pulumi destroy"
    cmds:
      - echo "Running pulumi destroy"
      - task infra:destroy
    silent: true
